### ISSUE TITLE
Vague installation instructions... got an error

### ISSUE THREAD

**Issue by 1blackbar** [ThereforeGames/txt2img2img#1]
Traceback (most recent call last):
  File "D:\sd\modules\ui.py", line 125, in f
    res = list(func(*args, **kwargs))
  File "D:\sd\webui.py", line 71, in f
    res = func(*args, **kwargs)
  File "D:\sd\modules\txt2img.py", line 34, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\sd\modules\scripts.py", line 139, in run
    processed = script.run(p, *script_args)
  File "D:\sd\scripts\txt2img2img.py", line 193, in run
    p.prompt_style,
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'prompt_style'

So, a video would be better, or just step by step, not sure why theres 2 json files one names exampe, should i name it after my subject name, its kinda unclear. Not really fond of overwriting files in my webui repo, is that necessary ?
Id like to try it out but we arent all devs that can jump into someone elses code and rock it immediately.
So... what should i do if my able to be stylised embedding with poor likeness is named "kry" but my overfit embedding is named "kryf ?

Heres what i got 
{
	"txt2img_term": "kryf",
	"img2img_term": "kry",
	"autoconfigure": true,
	"prompt_method":0,
	"negative_prompt": "include terms to offset any weaknesses in your subject",
	"sampler_name":"euler",
	"steps":25,
	"denoising_strength": 0.7,
	"cfg_scale": 9.5,
	"restore_faces": true,
	"bypass_color_correction":true
}

**Comment by ThereforeGames** [comment]
Hi,

Is your web UI up to date? It sounds like you might be on a slightly older version that lacks the "prompt_style" feature - I'll add a workaround for this soon.

> So... what should i do if my able to be stylised embedding with poor likeness is named "kry" but my overfit embedding is named "kryf ?

Swap your txt2img_term and img2img_term values.

txt2img runs first, and you want it to use a subject/embedding with high editability.

img2img runs next - that's where you provide a subject that struggles to listen to complex prompts. It may not understand prompts, but it will likely morph just fine with the initial image from the previous step.

Hope that helps.

**Comment by 1blackbar** [comment]
DId just that, installed from user bat but still got 

AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'prompt_style'

So i have it like this 

	"txt2img_term": "kry",
	"img2img_term": "kryf",
	"autoconfigure": false,
	"prompt_method":0,
	"negative_prompt": "include terms to offset any weaknesses in your subject",
	"sampler_name":"euler",
	"steps":25,
	"denoising_strength": 0.7,
	"cfg_scale": 9.5,
	"restore_faces": false,
	"bypass_color_correction":true
}

Still get prompt style error, i guess ill try wiping venv , this will take time


Ok i did wipe of the env, it still gives me no prompt style attribute... what the heck ?

**Comment by nerdyrodent** [comment]
Same here. Looks like img2img is expecting 2 styles?

```
    p = StableDiffusionProcessingImg2Img(
        sd_model=shared.sd_model,
        outpath_samples=opts.outdir_samples or opts.outdir_img2img_samples,
        outpath_grids=opts.outdir_grids or opts.outdir_img2img_grids,
        prompt=prompt,
        negative_prompt=negative_prompt,
        styles=[prompt_style, prompt_style2],
```

**Comment by ThereforeGames** [comment]
Issues have been resolved with yesterday's update.

A starter guide is now available here:

https://github.com/ThereforeGames/txt2img2img/blob/main/STARTER%20GUIDE.md

Marking this as closed, but feel free to open another issue if you have any other questions!
