### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by nerdyrodent** [ThereforeGames/txt2img2img#2]
Just wondering what the licence on your code? MIT?

Thanks!

**Comment by ThereforeGames** [comment]
Hi,

I'm a little hesitant to stamp a license on it as it relies on various Python modules as well as Automatic's codebase, but you are welcome to distribute, modify, adapt it as you see fit. Don't sell it or claim it as your own. Credit appreciated but not necessary!

Hopefully that will do for now.

Love your videos by the way. :-)

**Comment by nerdyrodent** [comment]
Awesome, thanks. Yeah, basically just want to make sure I can include it in a video ;)
