### ISSUE TITLE
Small README correction: AUTOMATIC1111 prompt weighting

### ISSUE THREAD

**Issue by hopibel** [ThereforeGames/txt2img2img#3]
Automatic's webui does support prompt weighting, but it's using () for emphasis and [] for de-emphasis (nestable) rather than specifying explicit weight values

**Comment by ThereforeGames** [comment]
Oh, good point! I'll have to revise the language in the docs.

The implementation of prompt weighting with the colon is very different, however - I haven't had much luck converting from Automatic's ((())) to get the same or even similar weighted results. When applied to my overtrained embeddings, each set of parentheses seems to degrade the image, whereas the colon enhances the details as expected. I need to take a look at what the code is actually doing and maybe see if I can include it in my script directly.
